apiVersion: v1
kind: ConfigMap
metadata:
  name: user-registration-app
data:
  ENV_MESSAGE: "Config Map Message"

---
apiVersion: v1
kind: Service
metadata:
  name: user-registration-app-service
spec:
  selector:
    app: user-registration-app
  ports:
  - name: user-registration-app-service-port
    protocol: TCP
    port: 3456
    targetPort: 5432
    nodePort: 30001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-registration-app-deployment
  labels:
    app: user-registration-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-registration-app
  template:
    metadata:
      labels:
        app: user-registration-app
    spec:
      containers:
      - name: user-registration-app
        image: sabsfilho/user-registration-app:latest
        envFrom:
        - configMapRef:
            name: user-registration-app
        resources:
          limits:
            memory: 200Mi
            cpu: 100m
          requests:
            memory: 200Mi
            cpu: 100m