apiVersion: v1
kind: ConfigMap
metadata:
  name: user-registration-app
data:
  ENV_MESSAGE: "Config Map Message"

---
apiVersion: v1
kind: Service
metadata:
  name: user-registration-app-service
spec:
  selector:
    app: user-registration-app
  ports:
  - name: user-registration-app-service-port
    protocol: TCP
    port: 3456
    targetPort: 5432
    nodePort: 30001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-registration-app-deployment
  labels:
    app: user-registration-app
    version: v1
  annotations:
    prometheus.io/port: '9216'
    prometheus.io/scrape: 'true'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greetings-service
  template:
    metadata:
      labels:
        app: user-registration-app
    spec:
      containers:
      - name: user-registration-app
        image: user-registration-app:1.0.1
        envFrom:
        - configMapRef:
            name: user-registration-app
        resources:
          limits:
            memory: 200Mi
            cpu: 100m
          requests:
            memory: 200Mi
            cpu: 100m
        livenessProbe:
          httpGet:
            path: /live
            port: 5432
        readinessProbe:
          httpGet:
            path: /ready
            port: 5432
        lifecycle:
          postStart:
            httpGet:
              path: /postStart
              port: 5432          
          preStop:
            httpGet:
              path: /preStop
              port: 5432          